version: '2.0'

services:
  web:
    build: ./src
    container_name: technition-web
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
  
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
