"""Entities test 1

Revision ID: e05690bac20b
Revises: 080c08c0f492
Create Date: 2024-06-05 14:13:12.959683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05690bac20b'
down_revision: Union[str, None] = '080c08c0f492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('purchase_available', sa.Boolean(), nullable=False))
    op.drop_column('hardware', 'internal_support')
    op.add_column('hardware_tech_stability', sa.Column('purchase_available', sa.Float(), nullable=True))
    op.add_column('hardware_tech_stability', sa.Column('cpu_util', sa.Float(), nullable=False))
    op.add_column('hardware_tech_stability', sa.Column('ram_util', sa.Float(), nullable=False))
    op.add_column('hardware_tech_stability', sa.Column('mem_util', sa.Float(), nullable=False))
    op.drop_column('hardware_tech_stability', 'purchasing_possibility')
    op.drop_column('hardware_tech_stability', 'utilization')
    op.drop_column('hardware_tech_stability', 'internal_support')
    op.alter_column('software', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('software_tech_stability', sa.Column('cpu_util', sa.Float(), nullable=False))
    op.add_column('software_tech_stability', sa.Column('ram_util', sa.Float(), nullable=False))
    op.add_column('software_tech_stability', sa.Column('mem_util', sa.Float(), nullable=False))
    op.add_column('software_tech_stability', sa.Column('srk', sa.Float(), nullable=False))
    op.add_column('software_tech_stability', sa.Column('purchase_available', sa.Float(), nullable=False))
    op.drop_column('software_tech_stability', 'internal_support')
    op.drop_column('software_tech_stability', 'utilization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software_tech_stability', sa.Column('utilization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('software_tech_stability', sa.Column('internal_support', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('software_tech_stability', 'purchase_available')
    op.drop_column('software_tech_stability', 'srk')
    op.drop_column('software_tech_stability', 'mem_util')
    op.drop_column('software_tech_stability', 'ram_util')
    op.drop_column('software_tech_stability', 'cpu_util')
    op.alter_column('software', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('hardware_tech_stability', sa.Column('internal_support', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('hardware_tech_stability', sa.Column('utilization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('hardware_tech_stability', sa.Column('purchasing_possibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('hardware_tech_stability', 'mem_util')
    op.drop_column('hardware_tech_stability', 'ram_util')
    op.drop_column('hardware_tech_stability', 'cpu_util')
    op.drop_column('hardware_tech_stability', 'purchase_available')
    op.add_column('hardware', sa.Column('internal_support', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('catalog', 'purchase_available')
    # ### end Alembic commands ###
